# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableCliCli }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cli
  name: cli
  namespace: "{{ .Values.nsPrefix }}"
spec:
  selector:
    matchLabels:
      app: cli
  template:
    metadata:
      labels:
        app: cli
      name: cli
    spec:
      containers:
      - image:  {{ .Values.image.cliImage}}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: "cli"
        env:
        - name: CLI_MODE
          value: daemon
        ports:
        - containerPort: 80
        - containerPort: 8080
          name: cli
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
