apiVersion: v1
kind: Service
metadata:
  name: framework
  namespace: "{{ .Values.nsPrefix }}-multicloud"
  labels:
    name: framework
  annotations:
    msb.onap.org/service-info: '[
    {
      "serviceName": "multicloud",
      "version": "v0",
      "url": "/api/multicloud/v0",
      "protocol": "REST",
      "port": "9001",
      "visualRange": "1"
    }
    ]'
spec:
  ports:
  - name: "framework-port"
    port: 9001
    nodePort: {{ .Values.nodePortPrefix }}91
  selector:
    app: framework
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: multicloud-vio
  namespace: "{{ .Values.nsPrefix }}-multicloud"
  labels:
    name: multicloud-vio
  annotations:
    msb.onap.org/service-info: '[
    {
      "serviceName": "multicloud-vio",
      "version": "v0",
      "url": "/api/multicloud-vio/v0",
      "protocol": "REST",
      "port": "9004",
      "visualRange": "1"
    }
    ]'

spec:
  ports:
  - name: "multicloud-port"
    port: 9004
    nodePort: {{ .Values.nodePortPrefix }}94
  selector:
    app: multicloud-vio
  type: NodePort
