# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableMulticloudMulticloudWindriver }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: multicloud-windriver
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.windRiverReplicas }}
  selector:
    matchLabels:
      app: multicloud-windriver
  template:
    metadata:
      labels:
        app: multicloud-windriver
      name: multicloud-windriver
    spec:
     hostname: multicloud-windriver
     containers:
     - env:
       - name: MSB_ADDR
         value: "{{ tpl .Values.msbgateway . }}"
       - name: MSB_PORT
         value: "{{ .Values.msbPort }}"
       - name: AAI_ADDR
         value: aai-service.{{ .Values.nsPrefix }}
       - name: AAI_PORT
         value: "8443"
       - name: AAI_SCHEMA_VERSION
         value: "v11"
       - name: AAI_USERNAME
         value: "AAI"
       - name: AAI_PASSWORD
         value: "AAI"
       name: multicloud-windriver
       volumeMounts:
       - mountPath: /opt/windriver/logs
         name: windriver-log
       image: {{ .Values.image.windriver }}
       imagePullPolicy: {{ .Values.pullPolicy }}
       ports:
       - containerPort: 9005
       livenessProbe:
         httpGet:
           path: /api/multicloud-titanium_cloud/v0/swagger.json
           port: 9005
           scheme: HTTP
         initialDelaySeconds: 30
         periodSeconds: 10
         timeoutSeconds: 10
         successThreshold: 1
         failureThreshold: 5
     restartPolicy: Always
     volumes:
     - name: windriver-log
       hostPath:
         path: {{ .Values.dataRootDir }}/{{ .Values.nsPrefix }}/multicloud/windriver/logs
     imagePullSecrets:
     - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
