# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableConsulConsulAgent }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: consul-agent
  name: consul-agent
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.consulAgentReplicas }}
  selector:
    matchLabels:
      app: consul-agent
  template:
    metadata:
      labels:
        app: consul-agent
      name: consul-agent
    spec:
      containers:
      - image: "{{ .Values.consulagentRegistry }}"
        command: ["/usr/local/bin/docker-entrypoint.sh"]
        args: ["agent","-client","0.0.0.0","-enable-script-checks","-join","consul-server.{{ .Values.nsPrefix }}"]
        name: consul-server
        volumeMounts:
        - mountPath: /consul/config
          name: consul-agent-config
        - mountPath: /consul/scripts
          name: consul-agent-scripts-config
        - mountPath: /consul/certs
          name: consul-agent-certs-config
      volumes:
      - configMap:
          name: consul-agent-configmap
        name: consul-agent-config
      - configMap:
          name: consul-agent-scripts-configmap
          defaultMode: 0755
        name: consul-agent-scripts-config
      - secret:
          secretName: consul-agent-certs-secret
        name: consul-agent-certs-config
#{{ end }}
