# Copyright © 2019 Amdocs, Bell Canada
# Copyright (c) 2020 Nordix Foundation, Modifications
# Modifications Copyright © 2020-2021 Nokia
# Modifications Copyright © 2023 Nordix Foundation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#################################################################
# Global configuration overrides.
#
# These overrides will affect all helm charts (ie. applications)
# that are listed below and are 'enabled'.
#################################################################
	global:
	  repository: 192.168.141.4:12360
	  pullPolicy: IfNotPresent
	  dockerHubRepository: 192.168.141.4:12360
	  repositoryCred:
	    user: argela
	    password: argela      
	  addTestingComponents: &testing true
	  centralizedLoggingEnabled: &centralizedLogging false
	aai:
	  enabled: true
	  global:
	    cassandra:
	      replicas: 1
	  aai-cassandra:
	    replicaCount: 1
	cassandra:
	  enabled: true
	  replicaCount: 2
	postgres:
	  enabled: false
	cli:
	  enabled: false
	cps:
	  enabled: false
	clamp:
	  enabled: false
	dcaegen2:
	  enabled: false
	dcaegen2-services:
	  enabled: false
	dcaemod:
	  enabled: false
	holmes:
	  enabled: false
	dmaap:
	  enabled: true
	  message-router:
	    enabled: true
	  dmaap-bc:
	    enabled: true
	  dmaap-dr-prov:
	    enabled: true
	  dmaap-dr-node:
	    enabled: true
	mariadb-galera:
	  enabled: true
	  replicaCount: 1
	msb:
	  enabled: true
	multicloud:
	  enabled: true
	nbi:
	  enabled: false
	oof:
	  enabled: false
	policy:
	  enabled: false
	robot:
	  enabled: true
	  config:
	    openStackEncryptedPasswordHere: "$OPENSTACK_ENCRYPTED_PASSWORD"
	  resources:
	    small:
	      limits:
		cpu: 1
		memory: 2Gi
	      requests:
		cpu: 10m
		memory: 100Mi
	sdc:
	  enabled: true
	sdnc:
	  enabled: true
	so:
	  enabled: true
	  config:
	    # openstack configuration
	    openStackUserName: "$OPENSTACK_USER_NAME"
	    openStackRegion: "$OPENSTACK_REGION"
	    openStackKeyStoneUrl: "$OPENSTACK_KEYSTONE_URL"
	    openStackServiceTenantName: "$OPENSTACK_TENANT_NAME"
	    openStackEncryptedPasswordHere: "$OPENSTACK_ENCRYPTED_PASSWORD"
	strimzi:
	  enabled: true
	  replicaCount: 1
	  strimzi-kafka-bridge:
	    enabled: true
	uui:
	  enabled: false
	vfc:
	  enabled: false
	vnfsdk:
	  enabled: true

  enabled: true
