#{{ if not .Values.disableUuiUui }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: uui
  name: uui
  namespace: "{{ .Values.nsPrefix }}-uui"
  annotations:
    msb.onap.org/service-info: '[
      {
          "serviceName": "usecaseui-gui",
          "version": "v1",
          "url": "/iui/usecaseui",
          "protocol": "UI"
          "port": "8080",
          "visualRange":"1|0"
      }
      ]'
spec:
  ports:
  - name: uui
    nodePort: {{ .Values.uuiPortPrefix }}98
    port: 8080
  selector:
    app: uui
  type: NodePort
#{{ end }}