nsPrefix: onap
pullPolicy: IfNotPresent
image:
  readiness: oomk8s/readiness-check:1.1.0
  consul: consul:0.9.3
  discovery: nexus3.onap.org:10001/onap/msb/msb_discovery:1.1.0-SNAPSHOT-latest
  apigateway: nexus3.onap.org:10001/onap/msb/msb_apigateway:1.1.0-SNAPSHOT-latest

consulPort: 8500
consulNodePort: 30500
msbConsulReplicas: 1

discoveryPort: 10081
discoveryNodePort: 30081
discoveryReplicas: 1

iagPort: 80
iagPort_https: 443
iagNodePort: 30080
iagNodePort_https: 30443
iagReplicas: 1

eagPort: 80
eagPort_https: 443
eagNodePort: 30082
eagNodePort_https: 30446
eagReplicas: 1
