nsPrefix: onap
pullPolicy: IfNotPresent
image:
  consul: consul:0.9.3
  discovery: nexus3.onap.org:10001/onap/msb/msb_discovery:1.0.0-STAGING-latest
  apigateway: nexus3.onap.org:10001/onap/msb/msb_apigateway:1.0.0-STAGING-latest

consulPort: 8500
consulNodePort: 30500

# Should remove cluster IP after domain name is supported by API gateway
discoveryClusterIP: 10.43.6.205
discoveryPort: 10081
discoveryNodePort: 30081
discoveryReplicas: 1

iagPort: 80
iagNodePort: 30080
iagReplicas: 1

eagPort: 80
eagNodePort: 30082
eagReplicas: 1
