nsPrefix: onap
pullPolicy: IfNotPresent
image:
  consul: consul:latest
  discovery: nexus3.onap.org:10001/onap/msb/msb_discovery:latest
  apigateway: nexus3.onap.org:10001/onap/msb/msb_discovery:latest

consulClusterIP: 10.43.6.204
consulPort: 8500
consulNodePort: 30500

discoveryClusterIP: 10.43.6.205
discoveryPort: 10081
discoveryNodePort: 30081
discoveryReplicas: 1

iagClusterIP: 10.43.6.206
iagPort: 80
iagNodePort: 30080
iagReplicas: 1

eagClusterIP: 10.43.6.207
eagPort: 80
eagNodePort: 30082
eagReplicas: 1