# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableVfcVfcHwvnfmdriver }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vfc-hwvnfmdriver
  namespace: "{{ .Values.nsPrefix }}"
spec:
  replicas: {{ .Values.hwvnfmdriver.replicas }}
  selector:
    matchLabels:
      app: vfc-hwvnfmdriver
  template:
    metadata:
      labels:
        app: vfc-hwvnfmdriver
      name: vfc-hwvnfmdriver
    spec:
      hostname: vfc-hwvnfmdriver
      containers:
      - args:
        image:  {{.Values.hwvnfmdriver.image}}
        name: "vfc-hwvnfmdriver"
        env:
        - name: MSB_ADDR
          value: {{ tpl .Values.msbaddr . }}
        ports:
        - containerPort: {{ .Values.hwvnfmdriver.port }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.hwvnfmdriver.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: "{{ .Values.pullPolicy }}"
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
