nsPrefix: onap
pullPolicy: IfNotPresent
image:
  kube2msb: nexus3.onap.org:10001/onap/oom/kube2msb
kubeMasterUrl: https://10.42.56.154:6443
discoveryUrl: http://msb-discovery.onap-msb:10081
kubeMasterAuthToken: QmFzaWMgTURrd056VXdSVEk1TVRGRk9UaEVOREJCTWprNlpHTnlaSGt4YzJsSVlsRlVZVU16WTFsUk1XWnZhV0UyY21GRWEwNUhkMDFDVWxORVRIUmlZUT09
