apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: "{{ .Values.nsPrefix }}-mso"
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      nodePort: 30252
  selector:
    app: mariadb
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: mso
  namespace: "{{ .Values.nsPrefix }}-mso"
  labels:
    app: mso
  annotations:
    msb.onap.org/service-info: '[
      {
          "serviceName": "so",
          "version": "v1",
          "url": "/ecomp/mso/infra",
          "protocol": "REST"
          "port": "8080",
          "visualRange":"1"
      },
      {
          "serviceName": "so-deprecated",
          "version": "v1",
          "url": "/ecomp/mso/infra",
          "protocol": "REST"
          "port": "8080",
          "visualRange":"1",
          "path":"/ecomp/mso/infra"
      }
      ]'
spec:
  selector:
    app: mso
  ports:
    - name: mso1
      port: 8080
      nodePort: 30223
    - name: mso2
      port: 3904
      nodePort: 30225
    - name: mso3
      port: 3905
      nodePort: 30224
    - name: mso4
      port: 9990
      nodePort: 30222
    - name: mso5
      port: 8787
      nodePort: 30250
  type: NodePort
