# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableDcaeDcaeCollectorCommonEvent }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dcae-collector-common-event
  namespace: "{{ .Values.nsPrefix }}"
spec:
  selector:
    matchLabels:
      app: dcae-collector-common-event
  template:
    metadata:
      labels:
        app: dcae-collector-common-event
      name: dcae-collector-common-event
    spec:
      containers:
      - image: {{ .Values.image.commonevent }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: dcae-collector-common-event
        ports:
          - containerPort: 8080
          - containerPort: 8443
          - containerPort: 9999
        env:
#        - name: KAFKA_ZOOKEEPER_CONNECT
#          value: "zookeeper:2181"
#        command:
#        - start-kafka.sh
        volumeMounts:
        - mountPath: /opt/app/manager/config
          name: dcae-collector-common-event-config
      restartPolicy: Always
      volumes:
      - name: dcae-collector-common-event-config
        hostPath:
          path: /dockerdata-nfs/{{ .Values.nsPrefix }}/dcae/common-event/config
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
