# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableVnfsdkRefrepo }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: refrepo
  name: vnfsdk-refrepo
  namespace: "{{ .Values.nsPrefix }}"
spec:
  selector:
    matchLabels:
      app: refrepo
  template:
    metadata:
      labels:
        app: refrepo
      name: vnfsdk-refrepo
    spec:
      initContainers:
      - command:
        - /root/ready.py
        args:
        - --container-name
        - postgres
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: "{{ .Values.image.readiness }}:{{ .Values.image.readinessVersion }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: vnfsdk-readiness
      containers:
      - image: {{ .Values.image.refrepoImage }}:{{ .Values.image.refrepoVersion }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: refrepo
        readinessProbe:
          tcpSocket:
            port: 8702
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
      - name: {{ .Values.nsPrefix }}-docker-registry-key
#{{ end }}
