# Copyright © 2017 Amdocs, Bell Canada
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#{{ if not .Values.disableSdcSdcEs }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sdc-es
  name: sdc-es
  namespace: "{{ .Values.nsPrefix }}"
spec:
  selector:
    matchLabels:
      app: sdc-es
  template:
    metadata:
      labels:
        app: sdc-es
      name: sdc-es
    spec:
      initContainers:
      - name: sdc-logs-init
        image: {{ .Values.image.ubuntuInit }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        command:
        - /bin/bash
        - "-c"
        - |
          mkdir -p /ubuntu-init/ASDC/ASDC-ES/
          mkdir -p /ubuntu-init/ASDC/ASDC-CS/
          mkdir -p /ubuntu-init/ASDC/ASDC-KB/
          mkdir -p /ubuntu-init/ASDC/ASDC-BE/
          mkdir -p /ubuntu-init/ASDC/ASDC-FE/
          chmod -R 777 /ubuntu-init/
      containers:
      - image: {{ .Values.image.sdcElasticsearch }}
        imagePullPolicy: {{ .Values.pullPolicy }}
        name: sdc-es
        env:
        - name: ENVNAME
          value: "AUTO"
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: ES_HEAP_SIZE
          value: "1024M"
        volumeMounts:
        - name: sdc-logs
          mountPath: /ubuntu-init/
        - mountPath: /root/chef-solo/environments/
          name: sdc-environments
        - mountPath: /etc/localtime
          name: sdc-localtime
          readOnly: true
        - mountPath: /var/lib/jetty/logs
          name: sdc-logs
        ports:
        - containerPort: 9200
        - containerPort: 9300
        readinessProbe:
          tcpSocket:
            port: 9200
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
        - name: sdc-environments
          configMap :
            name : sdc-environments-configmap
            defaultMode: 0755
        - name: sdc-localtime
          hostPath:
            path:  /etc/localtime
        - name:  sdc-logs
          hostPath:
            path:  {{ .Values.dataRootDir }}/{{ .Values.nsPrefix }}/sdc/logs
      imagePullSecrets:
      - name: "{{ .Values.nsPrefix }}-docker-registry-key"
#{{ end }}
