apiVersion: v1
kind: Service
metadata:
  name: msb-consul
  labels:
    app: msb-consul
spec:
  clusterIP: "{{ .Values.consulClusterIP }}"
  ports:
    - port: {{ .Values.consulPort }}
      nodePort: {{ .Values.consulNodePort }}
  selector:
    app: msb-consul
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: msb-discovery
  labels:
    app: msb-discovery
spec:
  clusterIP: "{{ .Values.discoveryClusterIP }}"
  ports:
    - port: {{ .Values.discoveryPort }}
      nodePort: {{ .Values.discoveryNodePort }}
  selector:
    app: msb-discovery
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: msb-iag
  labels:
    app: msb-iag
spec:
  clusterIP: "{{ .Values.iagClusterIP }}"
  ports:
    - port: {{ .Values.iagPort }}
      nodePort: {{ .Values.iagNodePort }}
  selector:
    app: msb-iag
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: msb-eag
  labels:
    app: msb-eag
spec:
  clusterIP: "{{ .Values.eagClusterIP }}"
  ports:
    - port: {{ .Values.eagPort }}
      nodePort: {{ .Values.eagNodePort }}
  selector:
    app: msb-eag
  type: NodePort